#Hugo configuration
title = "wqedsafd"
baseURL = "https:\/\/qweas.asd.dfg"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758381"
subfolder = ""
